### ISSUE TITLE
Add --noop flag

### ISSUE THREAD

**Issue by varac** [carlostrub/sisyphus#8]
I'm hesitant of trying sisyphus because afaik it potentially moves messaged on the first run.
It would be great to that a `--noop` flag (or sth similar) to see what it *would do* instead of actually doing.

**Comment by carlostrub** [comment]
Great idea. Will do.

**Comment by carlostrub** [comment]
Seems not to work yet... reopening.

**Comment by carlostrub** [comment]
works fine. double checked!
